- name: Ansible ping test
  hosts: all
  become: true
  tasks:
  - name: Ping Check using ping module
    ping:
  - name: Change Hello World to Hello Devops
    lineinfile:
      path: /app/src/App.js
      search_string: Hello World!
      line: Hello DevOps!
  - name: Bonus!
    lineinfile:
      path: /app/src/App.js
      insertafter: Hello DevOps!
      line: "###MARKER###"
  - 
    lineinfile:
      path: /app/src/App.js
      insertbefore: "###MARKER###"
      line: "{{ item }}"
    loop:
        - "</p>"
        - "<p>"
        - "Let's talk about open DevOps position! :)\n</p>\n<p>"
        - '<a href="https://www.linkedin.com/in/danielalejandrogamboafrayre/">https://www.linkedin.com/in/danielalejandrogamboafrayre/</a>'
  -
    lineinfile:
      path: /app/src/App.js
      line: "###MARKER###"
      state: absent
